### ISSUE TITLE
Bug breaking elevenlabslib

### ISSUE THREAD

**Issue by fiveisgreen** [lugia19/elevenlabslib#11]
I tried to run a trivial example use, found [here](https://github.com/Natorior/Python-ElevenLabs-Simple-TTS). That fails due to the following error: 

```
/elevenlabslib/helpers.py", line 52, in _pretty_print_POST
    req = res.requests
AttributeError: 'PreparedRequest' object has no attribute 'requests'
```

**Comment by lugia19** [comment]
Whoops. Fixed and uploaded v0.4.1 with the fix to pypi.
