### ISSUE TITLE
How to return the stream in an endpoint?

### ISSUE THREAD

**Issue by mcantillon21** [lugia19/elevenlabslib#22]
Let's say instead of playing the stream on one of the sound devices, I want to return the stream as a response to my endpoint. How do I do that?

**Comment by lugia19** [comment]
What do you mean by 'the stream'? The audio stream? Websockets?

**Comment by mcantillon21** [comment]
the audio stream. currently doing something like this but it still complains about not having an output sound device 

`              historyID, AudioStreamFuture = voice.generate_stream_audio_v2(
                  text_stream, 
                  PlaybackOptions(runInBackground=True),
                  GenerationOptions(latencyOptimizationLevel=4, use_speaker_boost=True, stability=0.73, similarity_boost=0.73),
                  WebsocketOptions(try_trigger_generation=True, chunk_length_schedule=[50])
              )
      
            def combine_streams():
                try:      
                  audio_data = AudioStreamFuture.result()
                  for chunk in audio_data:
                    yield chunk
                                
                except Exception as e:
                    print(e)
                        
            return Response(combine_streams(), mimetype="audio/mpeg")`

**Comment by lugia19** [comment]
sounddevice pretty much requires a device to output to by definition, in order to construct the outputstream - you're probably gonna have to figure out some way to achieve what you want to do.

If you can explain what you're trying to make, I can probably help.
