### ISSUE TITLE
sounddevice.PortAudioError

### ISSUE THREAD

**Issue by Ushi-Oni** [lugia19/elevenlabslib#28]
Hey all!

Getting this new error when utilizing generate_stream_audio_v2. I have the following setup for the call:

```python
xi_voice.generate_stream_audio_v2(
        prompt=prompt,
        generationOptions=elevenlabslib.GenerationOptions(
            stability=0.5,
            similarity_boost=0.1,
            style=0.777,
            use_speaker_boost=True,
        ),
        playbackOptions=elevenlabslib.PlaybackOptions(
            runInBackground=True,
            portaudioDeviceID=1,
            onPlaybackEnd=lambda: audio_lock.release()
        )
    )
```

Error: 
```markdown
sounddevice.PortAudioError: Error opening RawOutputStream: Invalid number of channels [PaErrorCode -9998]
```

Any ideas?

**Comment by lugia19** [comment]
Are you sure device index 1 is an output device? It might be an input. The code just tries to play a 1 channel file (mono) which should be supported by basically anything.

You can do
```py
import sounddevice
sounddevice.query_devices()
```

To see all the various device IDs.

**Comment by Ushi-Oni** [comment]
Yep! Exactly what it was. Wrote this quick little blurb to prompt the user so they can setup what device they'd like to use:
```python
print("Next, let's select the proper audio device.")
        p = pyaudio.PyAudio()
        for i in range(p.get_device_count()):
            device_info = p.get_device_info_by_index(i)
            if device_info['defaultSampleRate'] >= 44100.0 and device_info['maxOutputChannels'] > 0:
                print(f'#{device_info["index"]}: {device_info["name"]} \n')
                print(f'@{device_info["defaultSampleRate"]}Hz with default low/high output latency of '
                      f'[{device_info["defaultLowOutputLatency"]},{device_info["defaultHighOutputLatency"]}] \n')
                print('-'*100)
        while audio_device_index == -1:
            try:
                audio_device_index = int(input("Please enter the index id you'd like to select. Choose wisely."))
            except ValueError:
                print('Invalid selection, your input to the previous question was not a number. Try again.')
```

**Comment by lugia19** [comment]
👍, glad to hear that fixed it.

**Comment by Ushi-Oni** [comment]
Actually, I tried switching to sounddevice, used that to get a good index, and set that for the playback device, but now I'm getting a Failed to Load ASIO driver (ASIO error 0)

Specifically:
`
sounddevice.PortAudioError: Error opening RawOutputStream: Unanticipated host error [PaErrorCode -9999]: 'Failed to load ASIO driver' [ASIO error 0]
`

**Comment by lugia19** [comment]
It appears the support for ASIO can have some problems:
https://github.com/spatialaudio/python-sounddevice/issues/442

I would recommend trying one of the other audio backends. I usually use MME if on windows.
