### ISSUE TITLE
100 error code when use user.get_voices_by_name("Josh")

### ISSUE THREAD

**Issue by CroSSer23** [lugia19/elevenlabslib#29]
![image](https://github.com/lugia19/elevenlabslib/assets/25705091/095407f3-1fa4-4ebd-ae97-ceffb22996f2)
When a query occurs with user.get_voices_by_name("Josh")
It throws a 100 error and says Josh
but the problem is only on 1 PC. Python reinstalled. What can it be?

**Comment by lugia19** [comment]
You managed to get an old version that had some logging left enabled. Just update and it'll disappear, it's not an error.
