### ISSUE TITLE
Requirements for sounddevice and portaudio are missed

### ISSUE THREAD

**Issue by acriptis** [lugia19/elevenlabslib#3]
After installation of the lib I can not use it because the library misses some requirements. To use I have to install:
```sudo apt-get install libportaudio2```

And with pip:
```
sounddevice==0.4.6
```
Now it works, thanks!

**Comment by lugia19** [comment]
Yeah, I did notice that sounddevice is missing, but I didn't know you needed portaudio on linux. I'll be sure to note that in the readme. It'll be fixed later today.
