### ISSUE TITLE
AttributeError: 'Future' object has no attribute 'history_item_id'

### ISSUE THREAD

**Issue by robethang** [lugia19/elevenlabslib#32]
I get error [AttributeError: 'Future' object has no attribute 'history_item_id'] how to debug
![image](https://github.com/lugia19/elevenlabslib/assets/66782362/fd547f91-54e4-4f9d-9dc0-f74e648fe39f)

**Comment by lugia19** [comment]
Fixed in 0.22.3. But really, you shouldn't be using generate_audio_v2 anymore, it's deprecated.
