### ISSUE TITLE
Callback or notification when stream starts.

### ISSUE THREAD

**Issue by juankysoriano** [lugia19/elevenlabslib#6]
Hello, is there a way to get some sort of notification or to hook a callback so that when the stream starts, we can do an operation?

My use case is the following, there is, obviously, a slight delay before the time we perform a request and the stream starts getting listened from the audio output device. In my scenario I want to play a "loading sound" while it's still not streaming. Having what I mention would improve the user experience in my scenario a lot.

Thank you for this fantastic facility <3

**Comment by lugia19** [comment]
Added in 8b42fd6ec06ebedf0997839e4322849bfd669248
